name: Build application
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    runs-on: windows-latest
    - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build Tauri app
        run: npm run tauri build --target win
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tauri-win-build
          path: dist/

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: 'App Name v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false